/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as core from "./core";
export type { core };
import type * as dataServices from "./data-services";
export type { dataServices };
import type * as libs from "./libs";
export type { libs };
