/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ZLend2__factory } from "./ZLend2__factory";
export { ZLend2Manual__factory } from "./ZLend2Manual__factory";
