/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IExtendedERC20__factory } from "./IExtendedERC20__factory";
export { ZLend2__factory } from "./ZLend2__factory";
